## JHU Coursera R Programming Assignment 2: Lexical Scoping
## author: Chou, Shih-Han


## Running an operation in R may take a lot of time when there are many values to calculate. Thus, it would be very useful to cache a value if it will be used repeatedly.
## Inversing a matrix may be a time-consuming process when the matrix is large and complicated, so it's a lot more convenient to cache the result. The following two functions can work to cached the inverse of a matrix, and retrived the cached inverse. Using these two functions can save a lot of running time in R.

## The following function `makeCacheMatrix` is used to cache the inverse of a matrix. It generates a list of functions that could:
##      `set`: set a new matrix
##      `get`: retrieved cached matrix
##      `setinverse`: set a new inverse 
##      `getinverse`: retrieved cached inverse

makeCacheMatrix <- function(x = matrix()){
    i <- NULL                                                 ## The first step is to reset the value of `i`.
    set <- function(y){                                       ## Then, we define a function that is used to input a new matrix.
        x <<- y 
        i <<- NULL
    }
    get <- function() x                                       ## Define a function that is used to retrived cached matrix.
    setinverse <- function(inverse) i <<- inverse             ## This function is used to in put a new inversed matrix.
    getinverse <- function() i                                ## If an inverse has been cached, this function is used to retrieved it.
    list(set = set, get = get,                                ## Then, we put all the functions into a list.
         setinverse = setinverse, getinverse = getinverse)
}


## The following function `cacheSolve` calculates the inverse of a matrix set into the function `makeCacheMatrix`. Then, the inverse is then cached by the function `setinverse` in the list generated by `makeCacheMatrix`.

cacheSolve <- function(x, ...){
    i <- x$getinverse()                                       ## If the inverse has been cached, it will skip the calculation and retrieved the cached inverse.
    if(!is.null(i)){                                          ## If there is a chached inverse, this message will appear.
        message("getting cached inverse")
        return(i)
    }
    matrix <- x$get()                                         ## However, if there is a new matrix, it will then calculated the inverse of the matrix and than cached it.
    i <- solve(matrix, ...)
    x$setinverse(i)
    i                                                         ## The inverse of the matrix is returned.
}
